CREATE TABLE TB_STUDENT(
	STD_NO NUMBER CONSTRAINT TB_STUDENT_PK PRIMARY KEY,
	STD_NAME VARCHAR2(20) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	STD_GENDER CHAR(1) CHECK( STD_GENDER IN('M', 'F')),
	STD_SCORE CHAR(1) CHECK( STD_SCORE IN('A', 'B', 'C', 'D', 'F'))
);

SELECT * FROM TB_STUDENT
ORDER BY STD_NO ASC;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_STD_NO NOCACHE;

INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '학생일', '20', 'M', 'F');
INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '학생이', '21', 'F', 'D');
INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '학생삼', '22', 'M', 'C');
INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '학생사', '23', 'F', 'B');
INSERT INTO TB_STUDENT
VALUES(SEQ_STD_NO.NEXTVAL, '학생오', '24', 'M', 'A');


SELECT
	STD_NO ,
	STD_NAME ,
	STD_AGE ,
	STD_GENDER ,
	STD_SCORE 
FROM TB_STUDENT
WHERE STD_NO > 0
ORDER BY STD_NO ASC;

		UPDATE TB_STUDENT SET
		STD_NAME = ?,
		STD_AGE = ?,
		STD_GENDER = ?,
		STD_SCORE = ?
		WHERE STD_NO = ?